version: "3.8"

services:
  pgdb:
    container_name: msauthpgdb_compose
    image: kerroline/msauthpgdb
    restart: always
    networks:
      - msauthbridge
  authserver:
    container_name: msauthapp_compose
    image: kerroline/msauthapp
    ports:
      - '9999:80'
    restart: always
    depends_on:
      - pgdb
    networks:
      - msauthbridge

networks:
  msauthbridge:
    driver: bridge